id: IE3D1A455
legacy_id: P003215
ocr_import_info:
  bdrc_scan_id: W1KG5857
  source: bdrc
  ocr_info:
    timestamp: '2020-03-29T15:55:16'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T17:28:28.943428+00:00'
last_modified: 2022-09-01 01:29:14.826644
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG5857
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1KG5857
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཆོས་མངོན་པ་བསྡུས་པ།
  author: སེམས་དཔའ་རྡོ་རྗེ།
statistics:
  ocr_word_mean_confidence_index: 0.841506928413719
  ocr_word_median_confidence_index: 0.949999988079071
quality: null
bases:
  I1KG5883:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG5883
      total_pages: 596
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1KG5883.txt
    statistics:
      ocr_word_median_confidence_index: 0.9300000071525574
      ocr_word_mean_confidence_index: 0.8362348879220023
    legacy_id: v002
  I1KG5882:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG5882
      total_pages: 748
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG5882.txt
    statistics:
      ocr_word_median_confidence_index: 0.9599999785423279
      ocr_word_mean_confidence_index: 0.8457490498751316
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
