id: IE3D1A455
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T15:59:09+00:00'
last_modified: '2022-06-07T18:26:42.557103+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG5857
  title: ཆོས་མངོན་པ་བསྡུས་པ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '2882':
      image_group_id: I1KG5882
      title: ''
      total_pages: 748
      order: 1
      base_file: 2882.txt
    43D7:
      image_group_id: I1KG5883
      title: ''
      total_pages: 596
      order: 2
      base_file: 43D7.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
