id: P003215
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG5857
  title: ཆོས་མངོན་པ་བསྡུས་པ།
  author: ''
  volumes:
    8547af6b72d34dfb96e09562666e4a97:
      image_group_id: I1KG5882
      title: ''
      volume_number: 1
      total_pages: 748
      base_file: v001.txt
    26bfb96eef994749bd24c20aa5388ff1:
      image_group_id: I1KG5883
      title: ''
      volume_number: 2
      total_pages: 596
      base_file: v002.txt
